# Generated by Django 6.0.1 on 2026-01-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('discription', models.TextField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
    ]
