# Generated by Django 6.0.1 on 2026-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image_alter_products_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
