# Generated by Django 6.0.1 on 2026-02-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_price_products_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discription',
            new_name='text_blog',
        ),
    ]
